### PR TITLE
Rename TripLeg to Leg

### PR DESCRIPTION
**Pull request by ue71603**

### CODE REVIEW

**Comment by ue71603** [comment]
Fixes @180

**Comment by ue71603** [comment]
will do all examples, when content is ok for group.

**Comment by sgrossberndt** [comment]
OJP_FareSupport.xsd has a `TripLegRangeGroup` element referring to the elements `FromTripLegIdRef` and `ToTripLegIdRef` from OJP_Fare,xsd. Should those be renamed too?

**Comment by ue71603** [comment]
Discussion
•	#215
•	#230
 
They both would align things more to what it should be. However, (a) we don’t do it everywhere and we should move the id to an attribute in that case (b) in breaks a lot of implementations (c) It does not really simplify anything in a heavy way. I agree: It is hygiene, but I am not sure, if we should do it.
Please advise. For now I will leave them alone

**Comment by skinkie** [comment]
This is a breaking change... is this for 1.1.

**Comment by ue71603** [comment]
> This is a breaking change... is this for 1.1.

It is for 2.0

**Review by skinkie — APPROVED** [review]

**Review by herlitze — APPROVED** [review]

**Review by AndreasAtSBB — APPROVED** [review]
Checkt also the diff inside the HTML files.

**Review by trurlurl — APPROVED** [review]

**Review by skinkie — DISMISSED** [review]

**Review by sgrossberndt — CHANGES_REQUESTED** [review]
OJP_FareSupport.xsd has a TripLegRangeGroup element referring to the elements FromTripLegIdRef and ToTripLegIdRef from OJP_Fare,xsd. Shouldn't those be renamed too?

**Review by skinkie — APPROVED** [review]

**Review by sgrossberndt — APPROVED** [review]

**Review by skinkie — APPROVED** [review]

**Pull request merged**
