### PR TITLE
Feature visually impaired

### PR DESCRIPTION
**Pull request by skinkie**

### CODE REVIEW

**Comment by sgrossberndt** [comment]
Fixes https://github.com/VDVde/OJP/issues/26

**Comment by sgrossberndt** [comment]
This is a feature. Please add a new pull request against https://github.com/VDVde/OJP/tree/changes_for_v1.1

**Comment by skinkie** [comment]
@sgrossberndt thanks for the reminder. Lets fix everything directly after this meeting.

**Comment by skinkie** [comment]
@sgrossberndt it is now in https://github.com/VDVde/OJP/pull/36

**Pull request closed without merging**
