### PR TITLE
IsAlternativeOption

### PR DESCRIPTION
**Pull request by ue71603**
To make it clear, if the trip is the result from alternative options checking.

### CODE REVIEW

**Review by trurlurl — APPROVED** [review]

**Comment by skinkie** [comment]
Shouldn't it then have a reference to the alternative? If it already has it, why explicitly mention it?

**Comment by ue71603** [comment]
It doesn't have a reference and it is not clear, why the server did it. The server may have a myriad ideas how to define the alternative. So it just mentions it, that the result may not be considered optimal by what the request asked.

**Review by trurlurl — DISMISSED** [review]

**Comment by ue71603** [comment]
leave it at that.

**Review by trurlurl — APPROVED** [review]

**Comment by ue71603** [comment]
@skinkie : ready to merge....

**Pull request merged**
