### PR TITLE
Upstream siri

### PR DESCRIPTION
**Pull request by skinkie**
Yeah, this cleans things up. But the SIRI imports still has quite some polishing to do.

```
OJP_Requests.xsd:5: element import: Schemas parser warning : Element '{http://www.w3.org/2001/XMLSchema}import': Skipping import of schema located at 'SIRI/xsd/siri.xsd' for the namespace 'http://www.siri.org.uk/siri', since this namespace was already imported with the schema located at 'OJP.xsd'.
OJP_Fare.xsd:5: element import: Schemas parser warning : Element '{http://www.w3.org/2001/XMLSchema}import': Skipping import of schema located at 'siri_model/siri_reference-v2.0.xsd' for the namespace 'http://www.siri.org.uk/siri', since this namespace was already imported with the schema located at 'OJP.xsd'.
OJP_Common.xsd:5: element import: Schemas parser warning : Element '{http://www.w3.org/2001/XMLSchema}import': Skipping import of schema located at 'SIRI/xsd/siri.xsd' for the namespace 'http://www.siri.org.uk/siri', since this namespace was already imported with the schema located at 'OJP.xsd'.
OJP_ModesSupport.xsd:5: element import: Schemas parser warning : Element '{http://www.w3.org/2001/XMLSchema}import': Skipping import of schema located at 'SIRI/xsd/siri.xsd' for the namespace 'http://www.siri.org.uk/siri', since this namespace was already imported with the schema located at 'OJP.xsd'.
OJP_Utility.xsd:5: element import: Schemas parser warning : Element '{http://www.w3.org/2001/XMLSchema}import': Skipping import of schema located at 'SIRI/xsd/siri.xsd' for the namespace 'http://www.siri.org.uk/siri', since this namespace was already imported with the schema located at 'OJP.xsd'.
OJP_FacilitySupport.xsd:4: element import: Schemas parser warning : Element '{http://www.w3.org/2001/XMLSchema}import': Skipping import of schema located at 'siri_model/siri_facilities-v1.2.xsd' for the namespace 'http://www.siri.org.uk/siri', since this namespace was already imported with the schema located at 'OJP.xsd'.
OJP_Trips.xsd:5: element import: Schemas parser warning : Element '{http://www.w3.org/2001/XMLSchema}import': Skipping import of schema located at 'SIRI/xsd/siri.xsd' for the namespace 'http://www.siri.org.uk/siri', since this namespace was already imported with the schema located at 'OJP.xsd'.
OJP_JourneySupport.xsd:5: element import: Schemas parser warning : Element '{http://www.w3.org/2001/XMLSchema}import': Skipping import of schema located at 'SIRI/xsd/siri.xsd' for the namespace 'http://www.siri.org.uk/siri', since this namespace was already imported with the schema located at 'OJP.xsd'.
OJP_LocationSupport.xsd:5: element import: Schemas parser warning : Element '{http://www.w3.org/2001/XMLSchema}import': Skipping import of schema located at 'siri_model/siri_modes-v1.1.xsd' for the namespace 'http://www.siri.org.uk/siri', since this namespace was already imported with the schema located at 'OJP.xsd'.
OJP_SituationSupport.xsd:4: element import: Schemas parser warning : Element '{http://www.w3.org/2001/XMLSchema}import': Skipping import of schema located at 'SIRI/xsd/siri.xsd' for the namespace 'http://www.siri.org.uk/siri', since this namespace was already imported with the schema located at 'OJP.xsd'.
OJP_Locations.xsd:6: element import: Schemas parser warning : Element '{http://www.w3.org/2001/XMLSchema}import': Skipping import of schema located at 'siri_model/siri_modes-v1.1.xsd' for the namespace 'http://www.siri.org.uk/siri', since this namespace was already imported with the schema located at 'OJP.xsd'.
OJP_RequestSupport.xsd:4: element import: Schemas parser warning : Element '{http://www.w3.org/2001/XMLSchema}import': Skipping import of schema located at 'SIRI/xsd/siri.xsd' for the namespace 'http://www.siri.org.uk/siri', since this namespace was already imported with the schema located at 'OJP.xsd'.
OJP_StopEvents.xsd:5: element import: Schemas parser warning : Element '{http://www.w3.org/2001/XMLSchema}import': Skipping import of schema located at 'siri_model/siri_modes-v1.1.xsd' for the namespace 'http://www.siri.org.uk/siri', since this namespace was already imported with the schema located at 'OJP.xsd'.
SIRI/xsd/acsb/acsb_accessibility-v0.3.xsd:58: element import: Schemas parser warning : Element '{http://www.w3.org/2001/XMLSchema}import': Skipping import of schema located at 'SIRI/xsd/ifopt/ifopt_time-v0.2.xsd' for the namespace 'http://www.ifopt.org.uk/ifopt', since this namespace was already imported with the schema located at 'SIRI/xsd/ifopt/ifopt_allStopPlace-v0.3.xsd'.
SIRI/xsd/ifopt/ifopt_equipment-v0.3.xsd:59: element import: Schemas parser warning : Element '{http://www.w3.org/2001/XMLSchema}import': Skipping import of schema located at 'SIRI/xsd/siri_model/siri_feature_support-v2.0.xsd' for the namespace 'http://www.siri.org.uk/siri', since this namespace was already imported with the schema located at 'OJP.xsd'.
SIRI/xsd/ifopt/ifopt_modes-v0.2.xsd:53: element import: Schemas parser warning : Element '{http://www.w3.org/2001/XMLSchema}import': Skipping import of schema located at 'SIRI/xsd/siri_model/siri_modes-v1.1.xsd' for the namespace 'http://www.siri.org.uk/siri', since this namespace was already imported with the schema located at 'OJP.xsd'.
```

### CODE REVIEW

**Review by ue71603 — APPROVED** [review]

**Review by herlitze — APPROVED** [review]

**Comment by ue71603** [comment]
Stefan: Technically it works, but it needs a cleanup. What order
Merge late and then just clean it up.

**Comment by ue71603** [comment]
Formation and Capacity would profit from this one. Do you think we can get it ready, @skinkie ? Can I help? Should I try to rebase it?

**Comment by ue71603** [comment]
and we should use SIRI 2.1

**Comment by skinkie** [comment]
> Formation and Capacity would profit from this one. Do you think we can get it ready, @skinkie ? Can I help? Should I try to rebase it?

Rebasing is half of the work.

**Comment by skinkie** [comment]
#329 is doing it.

**Pull request closed without merging**
