### PR TITLE
Deploy the documentation tables of all branches

### PR DESCRIPTION
**Pull request by sgrossberndt**
Deployment to subdirectories named like the branches. This allows to preview the rendered documentation tables of each branch without having to solve merge conflicts in the repo all the time.

Fixes: #288

### CODE REVIEW

**Comment by sgrossberndt** [comment]
Sadly this doesnt work as deploying from pull requests is not allowed.

**Comment by sgrossberndt** [comment]
Giving up for now.. :-(

**Comment by ue71603** [comment]
@sgrossberndt  should we review it to prepare for merge?

**Comment by sgrossberndt** [comment]
No, as I wrote in https://github.com/VDVde/OJP/issues/288#issuecomment-1400005959 this does not work as intended.

**Comment by skinkie** [comment]
Since we go forward with xcore, I am closing this pull request.

**Pull request closed without merging**
