### PR TITLE
Moving HikingProfile and CyclingProfile out of TripContentFilter

### PR DESCRIPTION
**Pull request by trurlurl**
The proposal is to move HikingProfile and CyclingProfile out of TripContentFilterGroup since they affect the search behavior and not the information to be returned about the trips found (filtering the information would be my interpretation of what TripContentFilter should do).

### CODE REVIEW

**Review by ue71603 — COMMENTED** [review]
The proposed PR removes both Profiles from TripRefineRequest and TripChangeRequest.
Should I add them there as well?

**Comment by trurlurl** [comment]
> The proposed PR removes both Profiles from TripRefineRequest and TripChangeRequest. Should I add them there as well?

TripChangeRequestStructure - TripChangeParam - TripParams = TripParamStructure - TripMobilityFilter contains the profiles.

TripRefineRequest does not. I have a more fundamental question: We only have TripResult of the trip to be refined, this does not seem to include the initial TripParams - how is that sufficient to re-retrieve the trip?

**Comment by trurlurl** [comment]
> > The proposed PR removes both Profiles from TripRefineRequest and TripChangeRequest. Should I add them there as well?
> 
> TripChangeRequestStructure - TripChangeParam - TripParams = TripParamStructure - TripMobilityFilter contains the profiles.
> 
> TripRefineRequest does not. I have a more fundamental question: We only have TripResult of the trip to be refined, this does not seem to include the initial TripParams - how is that sufficient to re-retrieve the trip?

Proposal if it is not sufficient: add new `OriginalTripParams` to `TripRefineParamStructure`.

**Review by ue71603 — DISMISSED** [review]

**Comment by ue71603** [comment]
@herlitze   pls check for the filtergroup I added to trip refinement. I hope this is ok for you as well.

**Review by ue71603 — APPROVED** [review]

**Comment by ue71603** [comment]
@skinkie if ok, then pls approve and merge.

**Review by skinkie — APPROVED** [review]

**Pull request merged**
