### PR TITLE
Update SIRI to SIRI-2.0q

### LINKED ISSUE #25: Update SIRI
Update SIRI to most recent version in order to fix issues with xmllint and fix bugs

### PR DESCRIPTION
**Pull request by sgrossberndt**
Based on https://github.com/VDVde/OJP/pull/117 which must be merged first.
Fixes #25

### CODE REVIEW

**Comment by sgrossberndt** [comment]
Not sure yet if it is a good idea to update SIRI, the build passed but we do not have a lot of examples yet. Please have a thorough look at the changes done in https://github.com/VDVde/OJP/pull/118/commits/62a02b3440884e12539c17f5786d53257eeb4bd6. In question I think we should rather stick to the current SIRI implementation and update SIRI in OJP v2.0 instead.

**Comment by sgrossberndt** [comment]
This pull request should be discussed in our next meeting on 2020-12-03

**Comment by ue71603** [comment]
Next week the latest Siri version will be discussed in CEN. Should we wait for that or use 2.0q?

**Comment by sgrossberndt** [comment]
also see https://github.com/VDVde/OJP/issues/25#issuecomment-725288462

**Comment by sgrossberndt** [comment]
Closing this as we decided not to risk breaking anything related to this SIRI update in OJP v1.1 as we currently do not have a complete set of examples.

**Pull request closed without merging**
