### PR TITLE
Use siri:FareClass instead of own TravelClass enumeration

### PR DESCRIPTION
**Pull request by ue71603**
fixes: https://github.com/VDVde/OJP/issues/351

new: 
https://github.com/SIRI-CEN/SIRI/issues/109

### CODE REVIEW

**Comment by ue71603** [comment]
@Aurige  Why was it changed originally? Is using the SIRI stuff a good idea here

**Review by Aurige — APPROVED** [review]

**Comment by Aurige** [comment]
> @Aurige Why was it changed originally? Is using the SIRI stuff a good idea here

That's Ok, the SIRI enumeration is the exact same one as the NeTEx one :-)

**Review by skinkie — APPROVED** [review]

**Review by AndreasAtSBB — COMMENTED** [review]
Travel to Fare change. Looks fine!

**Review by AndreasAtSBB — APPROVED** [review]

**Comment by skinkie** [comment]
@Aurige or @sgrossberndt to merge.

**Review by sgrossberndt — APPROVED** [review]

**Pull request merged**
