### PR TITLE
Coherent use of ObjectIdType

### PR DESCRIPTION
**Pull request by trurlurl**
Some Result, Trip, and Leg IDs had been changed from xs:NMTOKEN to ObjectIdType, see #215.
References have not been consistently adapted accordingly. 

I hope it is correct that only some of the Results have an id (FareResult, StopEventResult, TripResult, and MultiPointTripResult).

### CODE REVIEW

**Review by skinkie — CHANGES_REQUESTED** [review]
lets discuss if we would like to have an TripIdType, LegIdType, etc.

**Comment by trurlurl** [comment]
I'm adding the discussion label, to discuss whether we'd like to have not simply ObjectIdType (for NeTEx objects), but TripIdType, LegIdType, etc. 

Would that be wanted mainly for validation purposes? What kind of validation tool? If it were something like "Data4PT NeTEx Validator", then I'd imagine that one wanted to do more intelligent checks than just syntax-based type checking - e.g., checking whether the referenced leg id really exists somewhere. But in order specify more intelligent checks, one would probably look at each element separately and not rely on the type.

**Comment by ue71603** [comment]
Stefan: For validation purposes this might be a good idea.
Norman: Why do we need identity constraint?
Stefan: From code generation it would help as well.

Appreciated, but not pressing.
==> if we find somebody to do it.

**Review by skinkie — APPROVED** [review]
Improvement in the future.

**Review by ue71603 — DISMISSED** [review]

**Review by ue71603 — APPROVED** [review]

**Review by skinkie — APPROVED** [review]

**Review by ue71603 — APPROVED** [review]

**Pull request merged**
