### PR TITLE
Use SIRI v2.1 from upstream as git submodule

### PR DESCRIPTION
**Pull request by skinkie**
At least try if this would work.

### CODE REVIEW

**Comment by skinkie** [comment]
@sgrossberndt I guess we miss a `git submodule update --init` in our github actions.

**Comment by skinkie** [comment]
@ue71603 feel free to update the examples that now fail.

**Comment by ue71603** [comment]
git for Desktop was not able to switch to the branch and messed up my local repository. 
Had to
* re clone it
* and in master in .git/config  remove in [submodules] the active=. part.
However, when I switched then to upstream_siri_v1.1. I got the problem that nothing was valid anymore and the SIRI subfolder in the repository was totally empty.

Which is clear, as it no longer does the automatic copying of SIRI. 


Perhaps some part of this is needed to copy the data into the folder: https://stackoverflow.com/questions/11069651/setting-upstream-to-a-submodule-or-how-to-include-a-github-fork-as-a-submodule

Currently it is clear why the tests are not running: No SIRI available locally.

**Comment by skinkie** [comment]
@ue71603 just to try it, can you manually clone SIRI in the SIRI subfolder, and see if you can get the files validating?

**Comment by ue71603** [comment]
@skinkie 
* copied it fully
image

* hat to switch the import in all OJP files from siri_all-v2.0 to ../siri/xsd/siri_model/siri_all.xsd
* had to switch some imports that used siri.xsd instead of siri_model/siri_all.all 
* fixing OJP.xsd  als with switching the import to <xs:include schemaLocation="./SIRI/xsd/siri_model/siri_all.xsd"/>  

Afterwards it validated. I try to do a PR (will add the full master of siri into the PR

**Comment by skinkie** [comment]
On Monday, March 6, 2023 8:38:14 PM CET, Matthias Günter wrote:
> @skinkie 
> * fixing OJP.xsd  als with switching the import to <xs:include 
> schemaLocation="./SIRI/xsd/siri_model/siri_all.xsd"/>  

Can you please check if it is ../SIRI or it should be ./SIRI?

-- 
Stefan

**Review by ue71603 — APPROVED** [review]

**Comment by ue71603** [comment]
> 

OJP.xsd is one level higher, so there it is only "./siri...." in the others it is "../siri"

**Comment by skinkie** [comment]
@ue71603 @sgrossberndt need to acknowledges ;-)

**Comment by sgrossberndt** [comment]
I have issues on my setup with this branch because of the former directory name "siri" and new directory name "SIRI". I propose to change the directory name back to "siri". What do you think?

**Comment by sgrossberndt** [comment]
You have to run `git submodule init ./siri` in order to fetch the SIRI sources

**Review by sgrossberndt — APPROVED** [review]

**Comment by skinkie** [comment]
> What do you think?

...annoying windows users.

**Comment by ue71603** [comment]
> > What do you think?
> 
> ...annoying windows users.

the worst....

**Comment by ue71603** [comment]
> You have to run `git submodule init ./siri` in order to fetch the SIRI sources

didn't fetch anything and I had to install git in addition to do it.

**Comment by ue71603** [comment]
All suggestions up to now don't work for me. And I am sorry, I need to do work on the functional stuff this month and can't affort to break the tool chain. I suggest we use a copied version of siri 2.1 for now and deal with this PR afterwards. I will even rebase it then. Having it done as a pipeline is not on the criticial path for this project. Stefan, I apologize for asking to do it first.

**Comment by ue71603** [comment]
Things I had to do... https://github.com/VDVde/OJP/wiki/Working-with-the-submodule  and I am not sure, if everybody can do it (one needs to install git, too.

**Comment by ue71603** [comment]
...and I think we need a discussion, why an automatic upstream is a good idea for this type of project...

**Pull request closed without merging**
