### PR TITLE
Cardinality of ArrivalFormationAssignment

### PR DESCRIPTION
**Pull request by trurlurl**
I think ArrivalFormationAssignment could occur multiple times - see discussion in #328 .

### CODE REVIEW

**Comment by ue71603** [comment]
@Aurige : Ok for me, but what do you think?

**Comment by skinkie** [comment]
Can someone give a quick example where a formation would have a different arrival time? Would this be when splitting and joining?

**Comment by ue71603** [comment]
I am not sure, if I have such an example.

**Comment by trurlurl** [comment]
Brainstorming kind of idea - multiple buses as a replacement of a train service ??

**Comment by ue71603** [comment]
Example needed for documentation. Otherwise unbounded ok.

**Comment by skinkie** [comment]
I am really not fond of the unbounded here.

**Comment by ue71603** [comment]
> I am really not fond of the unbounded here.

It is done that way in SIRI as well.

**Comment by skinkie** [comment]
> > I am really not fond of the unbounded here.
> 
> It is done that way in SIRI as well.

As bug or feature? ;-)

**Comment by ue71603** [comment]
I will do the example and we discuss it then, if it is needed. Will talk to @haeckerbaer

**Comment by ue71603** [comment]
@skinkie  @Aurige : I send you here the Swiss realisation guide with multiple DepartureFormationAssignments: https://www.öv-info.ch/sites/default/files/2023-04/siri_realisation-guide_pt_ch_v0.9.0.pdf

**Comment by skinkie** [comment]
You have a long train, where each carriage is assigned to a specific sector (quay).

**Comment by trurlurl** [comment]
@ue71603 You could approve it, I can't (having been the author of the PR).

**Review by ue71603 — APPROVED** [review]

**Pull request merged**
