### PR TITLE
Add TripStatusGroup

### PR DESCRIPTION
**Pull request by sgrossberndt**
Add a `TripStatusGroup` consisting of parameters which describe the current status of a trip.

### CODE REVIEW

**Review by pvgrumbkow — APPROVED** [review]

**Review by herlitze — DISMISSED** [review]

**Comment by sgrossberndt** [comment]
@skinkie Are you ok with https://github.com/VDVde/OJP/pull/116/commits/1cacd36a420d31546676bbf11090b458d8ed15aa too?

**Comment by sgrossberndt** [comment]
@skinkie Please add a review approval if you are fine with [this additional change](https://github.com/VDVde/OJP/commit/1cacd36a420d31546676bbf11090b458d8ed15aa) by me. Only after merging this I'll continue with the other pull requests.

**Review by pvgrumbkow — APPROVED** [review]

**Comment by sgrossberndt** [comment]
@herlitze @skinkie reviews please ;)

**Review by herlitze — APPROVED** [review]

**Comment by herlitze** [comment]
I am fine with this change, but I thought you wanted @skinkie to give his ok, since he was not part of the discussion in the meeting.

**Comment by sgrossberndt** [comment]
Thanks, yes, wanted to and will wait for his review too :)

**Comment by skinkie** [comment]
In "planned" de correct Transmodel definition opposed to "scheduled"?

**Comment by sgrossberndt** [comment]
This pacth was your proposal, @skinkie - please check whether its the correct term and update the branch and pull request if necessary. I will merge the other changes now, this pull request will have a merge conflict afterwards but currently this open question blocks further corrections.

**Comment by sgrossberndt** [comment]
Fixed merge conflict, pull request content is unchanged.

**Comment by sgrossberndt** [comment]
This patch was your proposal, @skinkie - please check whether its the correct term "unplanned" and update the branch and pull request if necessary. Let's discuss and merge it at 2020-12-03 if necessary.

**Review by pvgrumbkow — APPROVED** [review]

**Review by ue71603 — APPROVED** [review]

**Review by skinkie — APPROVED** [review]

**Comment by skinkie** [comment]
@sgrossberndt you were faster

**Pull request merged**
