### PR TITLE
copied SIRI 2.1 and adapted imports

### PR DESCRIPTION
**Pull request by ue71603**
without copying from upstream to see, if it works....

### CODE REVIEW

**Review by skinkie — APPROVED** [review]
I have checked it with XMLlint, works.

**Review by skinkie — APPROVED** [review]

**Review by trurlurl — CHANGES_REQUESTED** [review]
I don't know whether it makes sense to complain about minor problems in external code...

**Review by AndreasAtSBB — APPROVED** [review]
Changes in html dok seams to be fine.

**Comment by trurlurl** [comment]
@ue71603 Does this need some update to the documentation (the *documentation* labe is set)?

**Comment by ue71603** [comment]
@trurlurl 
* If it is mentioned somewhere in the documentation which SIRI is used, it should be adapted.
* If we use SIRI tables in chapter 8 perhaps a brief check is necessary, if it still fits. 
Otherwise I think that the real changes will manifest in other PR and the documentation comes from there.

**Pull request merged**
