### PR TITLE
Add scripts to generate documentation tables HTML from XSD

### PR DESCRIPTION
**Pull request by sgrossberndt**
Solves https://github.com/VDVde/OJP/issues/45 once all generation issues mentioned there are solved.

### CODE REVIEW

**Comment by sgrossberndt** [comment]
Travis could automatically generate the tables during build and either add them to the repository as an commit (to the same or a separate branch?) or upload them as a build artifact to some server.
Of course it would be also a valid approach not to generate them automatically.

**Comment by sgrossberndt** [comment]
Have two different themes:
1. General theme with links without chapter numbers
2. CEN theme without links with chapter numbers

Put all XSD files into one asciidoc and thus into one html file

Have Travis automatically generate those files and add them as a followup commit to the feature branch (like already done with the xmllint)

**Comment by sgrossberndt** [comment]
Done for now. There are still lots of issues but in my opinion this is a working base.
The HTML file can be viewed at https://vdvde.github.io/OJP/generated/OJP.html now.

**Comment by skinkie** [comment]
Let me compliment you first for this awesome work.

**Review by skinkie — APPROVED** [review]

**Review by herlitze — APPROVED** [review]

**Comment by sgrossberndt** [comment]
Shall we continue to work in this branch/pull request to fix the remaining problems with the HTML or merge this pull request to changes_for_v1.1 now and add issues and fixes to the branch? Either way is fine for me, but maybe its easier to merge now not to have merge conflicts due to the necessary cleanups in the annotation->documentation.
@pvgrumbkow @skinkie @herlitze @ue71603

**Comment by pvgrumbkow** [comment]
I opt for merging now.

**Pull request merged**
